# Generated by Django 3.0.6 on 2020-06-04 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_auto_20200527_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='serviceprovider',
            field=models.ManyToManyField(blank=True, to='home.ServiceProvider'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='user',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ServiceRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('service', models.ManyToManyField(to='home.Service')),
                ('servicecategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.ServiceCategory')),
            ],
        ),
    ]
