# Generated by Django 3.0.6 on 2020-06-13 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_serviceregistration_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.BooleanField(default=True)),
                ('delivery_duration', models.CharField(blank=True, max_length=200, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client_confirmation', models.BooleanField(default=False)),
                ('payment_made', models.BooleanField(default=False)),
                ('service_dispatched', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('vendor_paid', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Service')),
                ('service_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_user', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
