# Generated by Django 3.0.6 on 2020-08-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceregistration',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
