# Generated by Django 3.0.6 on 2020-09-22 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_fcmusertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceregistration',
            name='servicecategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ServiceCategory'),
        ),
        migrations.AlterField(
            model_name='serviceregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Service'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to=settings.AUTH_USER_MODEL),
        ),
    ]
